name: pixelrepa
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pip=22.3
  - pytorch-cuda=12.4
  - pytorch=2.5.1
  - torchvision=0.20.1
  - numpy=1.22
  - pip:
    - diffusers==0.38.0
    - pillow==12.2.0
    - safetensors==0.4.5
