import argparse
import json
import sys
from pathlib import Path

import torch
from typing import Optional

try:
    from src.diffusers.models.transformers.pixelrepa_weights import PIXELREPA_PRESET_CONFIGS
    from src.diffusers.models.transformers.transformer_pixelrepa import PixelREPATransformer2DModel
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from src.diffusers.models.transformers.pixelrepa_weights import PIXELREPA_PRESET_CONFIGS
    from src.diffusers.models.transformers.transformer_pixelrepa import PixelREPATransformer2DModel


def get_args():
    parser = argparse.ArgumentParser(description="Convert diffusers PixelREPA model back to checkpoint format.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to diffusers model directory.")
    parser.add_argument("--output_path", type=str, required=True, help="Output PixelREPA checkpoint path (.pth).")
    parser.add_argument(
        "--ema_mode",
        type=str,
        default="copy_to_both",
        choices=["none", "copy_to_both"],
        help="How to reconstruct EMA states in the PixelREPA checkpoint.",
    )
    parser.add_argument(
        "--epoch",
        type=int,
        default=0,
        help="Epoch value to store in the output checkpoint.",
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional conversion_metadata.json generated by convert_pixelrepa_to_diffusers.py.",
    )
    return parser.parse_args()


def _first_present(mapping, *keys):
    for key in keys:
        if key in mapping and mapping[key] is not None:
            return mapping[key]
    return None


def _config_first(config, *keys, default=None, required: bool = False):
    for key in keys:
        value = getattr(config, key, None)
        if value is not None:
            return value
    if required:
        raise ValueError(f"Missing required config fields: {keys}")
    return default


def _infer_model_type_from_config(model_config) -> Optional[str]:
    sample_size = _config_first(model_config, "sample_size", "image_size")
    patch_size = _config_first(model_config, "patch_size")
    hidden_size = _config_first(model_config, "hidden_size")
    num_layers = _config_first(model_config, "num_layers", "depth")
    num_attention_heads = _config_first(model_config, "num_attention_heads", "num_heads")

    for model_type, preset in PIXELREPA_PRESET_CONFIGS.items():
        if (
            int(sample_size) == int(preset["sample_size"])
            and int(patch_size) == int(preset["patch_size"])
            and int(hidden_size) == int(preset["hidden_size"])
            and int(num_layers) == int(preset["num_layers"])
            and int(num_attention_heads) == int(preset["num_attention_heads"])
        ):
            return model_type
    return None


def main():
    args = get_args()

    model_path = Path(args.model_path)
    transformer_path = model_path / "transformer" if (model_path / "transformer").exists() else model_path
    model = PixelREPATransformer2DModel.from_pretrained(str(transformer_path))
    checkpoint = model.to_pixelrepa_checkpoint(ema_mode=args.ema_mode)
    checkpoint["epoch"] = args.epoch
    checkpoint["optimizer"] = {}

    metadata_path = Path(args.metadata_path) if args.metadata_path else model_path / "conversion_metadata.json"
    metadata_args = None
    if metadata_path.exists():
        with metadata_path.open("r", encoding="utf-8") as file:
            metadata = json.load(file)
        metadata_args = metadata.get("pixelrepa_args") or metadata.get("jit_args")

    source_args = metadata_args or {}

    model_type = _first_present(source_args, "model_type", "model_name", "model")
    if model_type is None:
        model_type = _config_first(model.config, "model_type", "model_name", default=None)
    if model_type is None:
        model_type = _infer_model_type_from_config(model.config)
    if model_type is None:
        raise ValueError(
            "Could not infer PixelREPA model_type from config. "
            "Pass --metadata_path generated by convert_pixelrepa_to_diffusers.py."
        )

    sample_size = _first_present(source_args, "sample_size", "image_size", "img_size")
    if sample_size is None:
        sample_size = _config_first(model.config, "sample_size", "image_size", required=True)

    num_class_embeds = _first_present(source_args, "num_class_embeds", "num_classes", "class_num")
    if num_class_embeds is None:
        num_class_embeds = _config_first(model.config, "num_class_embeds", "num_classes", required=True)

    attention_dropout = _first_present(source_args, "attention_dropout", "attn_dropout")
    if attention_dropout is None:
        attention_dropout = _config_first(model.config, "attention_dropout", "attn_dropout", default=0.0)

    dropout = _first_present(source_args, "dropout", "proj_dropout")
    if dropout is None:
        dropout = _config_first(model.config, "dropout", "proj_dropout", default=0.0)

    args_dict = {
        "model": model_type,
        "img_size": sample_size,
        "class_num": num_class_embeds,
        "attn_dropout": attention_dropout,
        "proj_dropout": dropout,
        "model_type": model_type,
        "sample_size": sample_size,
        "num_class_embeds": num_class_embeds,
        "attention_dropout": attention_dropout,
        "dropout": dropout,
    }
    checkpoint["args"] = argparse.Namespace(**args_dict)

    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, str(output_path))
    print(f"Saved PixelREPA checkpoint to: {output_path}")


if __name__ == "__main__":
    main()
